name: Build CarQt

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Main
    container: 
        image: ghcr.io/gaitovrat/bachelor-qt:latest
        credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.container_token }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -S . -B build -G Ninja

    - name: Build
      run: cmake --build build --parallel
